"""OpenClaw adapter used for the reported Harbor 0.3.0 evaluations.

The recovered experiment adapter installed ``openclaw@2026.4.15`` in each
task sandbox and resolved Node 22 to v22.22.3. This release pins both
resolved versions. It uses an OpenAI-compatible chat-completions endpoint,
starts the local gateway, and runs the same two-turn interaction:

  Turn 1: the instruction + hint to use skills
  Turn 2: "Please proceed and complete the task."

Env vars read from the host and propagated into the sandbox:

  OPENCLAW_PROVIDER_BASE_URL    (required)
  OPENCLAW_PROVIDER_API_KEY     (required)
  OPENCLAW_GATEWAY_TOKEN        (optional; generated by run_cell.sh)
  OPENCLAW_MODEL_CONTEXT_WINDOW (optional; default 1000000)
  OPENCLAW_MODEL_MAX_TOKENS     (optional; default 8192)
  OPENCLAW_TURN_TIMEOUT_SEC     (optional; default 600)

Unlike the retained runtime copy, this publication-safe copy does not
archive ``~/.openclaw`` after the run because that directory contains the
provider credential. Removing that post-run copy does not change either
agent turn or verifier execution.
"""

import os
import shlex

from harbor.agents.installed.base import BaseInstalledAgent, with_prompt_template
from harbor.environments.base import BaseEnvironment
from harbor.models.agent.context import AgentContext
from harbor.models.trial.paths import EnvironmentPaths


class OpenClaw(BaseInstalledAgent):
    """OpenClaw CLI agent, installed via npm inside the sandbox."""

    _OUTPUT_FILENAME = "openclaw.txt"

    @staticmethod
    def name() -> str:
        # Loaded via Harbor's --agent-import-path; no factory patch is needed.
        return "openclaw"

    def get_version_command(self) -> str | None:
        return (
            'export NVM_DIR="$HOME/.nvm"; '
            'if [ -s "$NVM_DIR/nvm.sh" ]; then . "$NVM_DIR/nvm.sh"; '
            'nvm use 22.22.3 >/dev/null 2>&1 || true; fi; '
            "openclaw --version"
        )

    def parse_version(self, stdout: str) -> str:
        text = stdout.strip()
        for line in text.splitlines():
            line = line.strip()
            if line:
                return line
        return text

    async def install(self, environment: BaseEnvironment) -> None:
        # The original adapter selected major 22, which resolved to v22.22.3
        # in the retained runtime. Pin that resolved version for replication.
        await self.exec_as_agent(
            environment,
            command=(
                "set -e; "
                "export NVM_DIR=\"$HOME/.nvm\"; "
                "if [ ! -s \"$NVM_DIR/nvm.sh\" ]; then "
                "  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash; "
                "fi; "
                ". \"$NVM_DIR/nvm.sh\"; "
                "nvm install 22.22.3 >/dev/null; "
                "nvm alias default 22.22.3 >/dev/null; "
                "nvm use 22.22.3 >/dev/null; "
                "node --version; "
                # Exact npm version used by the reported May 2026 trials.
                "npm install -g openclaw@2026.4.15; "
                "openclaw --version"
            ),
            timeout_sec=900,
        )

    def populate_context_post_run(self, context: AgentContext) -> None:
        pass

    @with_prompt_template
    async def run(
        self,
        instruction: str,
        environment: BaseEnvironment,
        context: AgentContext,
    ) -> None:
        if not self.model_name:
            raise ValueError("Model name is required (e.g. deepseek-v4-flash)")

        # Strip an optional Harbor-side provider prefix.
        bare_model = self.model_name.split("/", 1)[-1]

        base_url = os.environ.get("OPENCLAW_PROVIDER_BASE_URL")
        api_key = os.environ.get("OPENCLAW_PROVIDER_API_KEY")
        if not base_url or not api_key:
            raise ValueError(
                "OPENCLAW_PROVIDER_BASE_URL and OPENCLAW_PROVIDER_API_KEY "
                "must be set on the host and are forwarded to the sandbox."
            )

        gateway_token = os.environ.get("OPENCLAW_GATEWAY_TOKEN", "harbor-token")
        ctx_window = os.environ.get("OPENCLAW_MODEL_CONTEXT_WINDOW", "1000000")
        max_tokens = os.environ.get("OPENCLAW_MODEL_MAX_TOKENS", "8192")
        turn_timeout = int(os.environ.get("OPENCLAW_TURN_TIMEOUT_SEC", "600"))

        env = {
            "OPENCLAW_PROVIDER_BASE_URL": base_url,
            "OPENCLAW_PROVIDER_API_KEY": api_key,
            "OPENCLAW_GATEWAY_TOKEN": gateway_token,
            "OPENCLAW_MODEL_CONTEXT_WINDOW": ctx_window,
            "OPENCLAW_MODEL_MAX_TOKENS": max_tokens,
            "OPENCLAW_MODEL": bare_model,
        }

        escaped_instruction = shlex.quote(instruction)
        followup = shlex.quote(
            "Please proceed and complete the task. Run any setup or "
            "preparation steps the skill requires first."
        )
        instruction_with_hint = shlex.quote(
            instruction + "\n\nMake sure to follow any setup or prerequisite "
            "steps defined in the available skills."
        )
        agent_out = EnvironmentPaths.agent_dir / self._OUTPUT_FILENAME

        setup_command = r"""
set -eu
mkdir -p "$HOME/.openclaw/logs"
cat > "$HOME/.openclaw/openclaw.json" <<OCJSON
{
  "agents": {
    "defaults": {
      "workspace": "/root",
      "model": { "primary": "litellm/${OPENCLAW_MODEL}" }
    }
  },
  "gateway": {
    "mode": "local",
    "auth": { "mode": "token", "token": "${OPENCLAW_GATEWAY_TOKEN}" },
    "port": 18789,
    "bind": "loopback",
    "controlUi": { "allowInsecureAuth": false },
    "nodes": { "denyCommands": [] }
  },
  "tools": {
    "profile": "coding",
    "fs": { "workspaceOnly": true },
    "exec": { "security": "full", "ask": "off" }
  },
  "models": {
    "mode": "merge",
    "providers": {
      "litellm": {
        "baseUrl": "${OPENCLAW_PROVIDER_BASE_URL}",
        "apiKey": "${OPENCLAW_PROVIDER_API_KEY}",
        "api": "openai-completions",
        "models": [{
          "id": "${OPENCLAW_MODEL}",
          "name": "${OPENCLAW_MODEL}",
          "reasoning": true,
          "input": ["text"],
          "cost": { "input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0 },
          "contextWindow": ${OPENCLAW_MODEL_CONTEXT_WINDOW},
          "maxTokens": ${OPENCLAW_MODEL_MAX_TOKENS}
        }]
      }
    }
  },
  "auth": { "profiles": { "litellm:default": { "provider": "litellm", "mode": "api_key" } } },
  "approvals": { "exec": { "enabled": false } },
  "skills": { "install": { "nodeManager": "npm" } }
}
OCJSON
"""

        run_command = f"""
set -eu
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then . "$NVM_DIR/nvm.sh"; nvm use 22.22.3 >/dev/null 2>&1 || true; fi
# start gateway in background and trap cleanup on exit (keeps sandbox footprint small)
nohup openclaw gateway >> "$HOME/.openclaw/logs/gateway.log" 2>&1 &
GATEWAY_PID=$!
cleanup() {{
    kill $GATEWAY_PID 2>/dev/null || true
    # drop secrets and session state; trajectories are kept under /logs/agent/
    rm -rf "$HOME/.openclaw/openclaw.json" "$HOME/.openclaw/sessions" \\
           "$HOME/.openclaw/logs" "$HOME/.openclaw/cache" 2>/dev/null || true
}}
trap cleanup EXIT
sleep 8

mkdir -p "$(dirname {agent_out})"
SID="harbor-$(date +%s)-$$"
echo "=== openclaw turn 1  (session=$SID  model={bare_model}) ===" >> {agent_out}
openclaw agent --session-id "$SID" -m {instruction_with_hint} \\
    --json --timeout {turn_timeout} 2>&1 | tee -a {agent_out}
sleep 3
echo "" >> {agent_out}
echo "=== openclaw turn 2 ===" >> {agent_out}
openclaw agent --session-id "$SID" -m {followup} \\
    --json --timeout {turn_timeout} 2>&1 | tee -a {agent_out}
"""

        await self.exec_as_agent(
            environment,
            command=setup_command,
            env=env,
        )
        try:
            await self.exec_as_agent(
                environment,
                command=run_command,
                env=env,
                timeout_sec=turn_timeout * 2 + 60,
            )
        finally:
            # Best-effort belt-and-suspenders cleanup in case the trap above
            # didn't fire (e.g. timeout-killed shell).
            try:
                await self.exec_as_agent(
                    environment,
                    command=(
                        "pkill -f 'openclaw gateway' 2>/dev/null || true; "
                        "rm -rf \"$HOME/.openclaw/openclaw.json\" "
                        "\"$HOME/.openclaw/sessions\" "
                        "\"$HOME/.openclaw/cache\" 2>/dev/null || true"
                    ),
                )
            except Exception:
                pass
